apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configs
  namespace: hotrod
data:
  config: |
    server {
        listen       80;
        server_name  localhost;

        location / {
            root html;
            index index.html index.htm;
        }

        error_page  404              /404.html;
    }
