apiVersion: v1
kind: Service
metadata:
  name: hotrod-api
  namespace: hotrod
  labels:
    appName: hotrod-api
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  ports:
  - name: http-hotrod-api
    port: 80
  type: ClusterIP
  selector:
    appName: hotrod-api
---
apiVersion: apps/v1beta2 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: hotrod-api
  namespace: hotrod
spec:
  selector:
    matchLabels:
      appName: hotrod-api
  replicas: 3
  template:
    metadata:
      labels:
        appName: hotrod-api
    spec:
      containers:
      - name: hotrod-api
        imagePullPolicy: Always
        image: index.docker.io/hantaowang/hotrod-api:log
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
